-- V1200__index_coverage.sql
---------------------------------------------------------
-- Создание таблицы experiment_01 и индексов
-- Автор: Ваше имя
-- Содержит:
-- 1. Таблица experiment_01
-- 2. Генерация данных
-- 3. Создание всех возможных B-Tree индексов

-- Создание таблицы experiment_01
CREATE TABLE IF NOT EXISTS experiment_01 (
    A bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    B varchar(100),
    C timestamp,
    D bigint
);

-- 2. Генерация данных
INSERT INTO experiment_01 (B, C, D)
select
    md5(random()::varchar) as B,
    TIMESTAMP '2020-01-01 00:00:00' + (random() * 365) * interval '1 day' as C,
    100 + (random() * 200)::bigint as D
from generate_series(1, 300000);

-- 3. Создание индексов для каждого столбца
CREATE INDEX IF NOT EXISTS experiment_01_A_idx ON experiment_01 (A);
CREATE INDEX IF NOT EXISTS experiment_01_B_idx ON experiment_01 (B);
CREATE INDEX IF NOT EXISTS experiment_01_C_idx ON experiment_01 (C);
CREATE INDEX IF NOT EXISTS experiment_01_D_idx ON experiment_01 (D);
CREATE INDEX IF NOT EXISTS experiment_01_A_B_idx ON experiment_01 (A, B);
CREATE INDEX IF NOT EXISTS experiment_01_B_A_idx ON experiment_01 (B, A);
CREATE INDEX IF NOT EXISTS experiment_01_A_C_idx ON experiment_01 (A, C);
CREATE INDEX IF NOT EXISTS experiment_01_C_A_idx ON experiment_01 (C, A);
CREATE INDEX IF NOT EXISTS experiment_01_A_D_idx ON experiment_01 (A, D);
CREATE INDEX IF NOT EXISTS experiment_01_D_A_idx ON experiment_01 (D, A);
CREATE INDEX IF NOT EXISTS experiment_01_B_C_idx ON experiment_01 (B, C);
CREATE INDEX IF NOT EXISTS experiment_01_C_B_idx ON experiment_01 (C, B);
CREATE INDEX IF NOT EXISTS experiment_01_B_D_idx ON experiment_01 (B, D);
CREATE INDEX IF NOT EXISTS experiment_01_D_B_idx ON experiment_01 (D, B);
CREATE INDEX IF NOT EXISTS experiment_01_C_D_idx ON experiment_01 (C, D);
CREATE INDEX IF NOT EXISTS experiment_01_D_C_idx ON experiment_01 (D, C);
CREATE INDEX IF NOT EXISTS experiment_01_A_B_C_idx ON experiment_01 (A, B, C);
CREATE INDEX IF NOT EXISTS experiment_01_A_C_B_idx ON experiment_01 (A, C, B);
CREATE INDEX IF NOT EXISTS experiment_01_B_A_C_idx ON experiment_01 (B, A, C);
CREATE INDEX IF NOT EXISTS experiment_01_B_C_A_idx ON experiment_01 (B, C, A);
CREATE INDEX IF NOT EXISTS experiment_01_C_A_B_idx ON experiment_01 (C, A, B);
CREATE INDEX IF NOT EXISTS experiment_01_C_B_A_idx ON experiment_01 (C, B, A);
CREATE INDEX IF NOT EXISTS experiment_01_A_B_D_idx ON experiment_01 (A, B, D);
CREATE INDEX IF NOT EXISTS experiment_01_A_D_B_idx ON experiment_01 (A, D, B);
CREATE INDEX IF NOT EXISTS experiment_01_B_A_D_idx ON experiment_01 (B, A, D);
CREATE INDEX IF NOT EXISTS experiment_01_B_D_A_idx ON experiment_01 (B, D, A);
CREATE INDEX IF NOT EXISTS experiment_01_D_A_B_idx ON experiment_01 (D, A, B);
CREATE INDEX IF NOT EXISTS experiment_01_D_B_A_idx ON experiment_01 (D, B, A);
CREATE INDEX IF NOT EXISTS experiment_01_A_C_D_idx ON experiment_01 (A, C, D);
CREATE INDEX IF NOT EXISTS experiment_01_A_D_C_idx ON experiment_01 (A, D, C);
CREATE INDEX IF NOT EXISTS experiment_01_C_A_D_idx ON experiment_01 (C, A, D);
CREATE INDEX IF NOT EXISTS experiment_01_C_D_A_idx ON experiment_01 (C, D, A);
CREATE INDEX IF NOT EXISTS experiment_01_D_A_C_idx ON experiment_01 (D, A, C);
CREATE INDEX IF NOT EXISTS experiment_01_D_C_A_idx ON experiment_01 (D, C, A);
CREATE INDEX IF NOT EXISTS experiment_01_B_C_D_idx ON experiment_01 (B, C, D);
CREATE INDEX IF NOT EXISTS experiment_01_B_D_C_idx ON experiment_01 (B, D, C);
CREATE INDEX IF NOT EXISTS experiment_01_C_B_D_idx ON experiment_01 (C, B, D);
CREATE INDEX IF NOT EXISTS experiment_01_C_D_B_idx ON experiment_01 (C, D, B);
CREATE INDEX IF NOT EXISTS experiment_01_D_B_C_idx ON experiment_01 (D, B, C);
CREATE INDEX IF NOT EXISTS experiment_01_D_C_B_idx ON experiment_01 (D, C, B);
CREATE INDEX IF NOT EXISTS experiment_01_A_B_C_D_idx ON experiment_01 (A, B, C, D);
CREATE INDEX IF NOT EXISTS experiment_01_A_B_D_C_idx ON experiment_01 (A, B, D, C);
CREATE INDEX IF NOT EXISTS experiment_01_A_C_B_D_idx ON experiment_01 (A, C, B, D);
CREATE INDEX IF NOT EXISTS experiment_01_A_C_D_B_idx ON experiment_01 (A, C, D, B);
CREATE INDEX IF NOT EXISTS experiment_01_A_D_B_C_idx ON experiment_01 (A, D, B, C);
CREATE INDEX IF NOT EXISTS experiment_01_A_D_C_B_idx ON experiment_01 (A, D, C, B);
CREATE INDEX IF NOT EXISTS experiment_01_B_A_C_D_idx ON experiment_01 (B, A, C, D);
CREATE INDEX IF NOT EXISTS experiment_01_B_A_D_C_idx ON experiment_01 (B, A, D, C);
CREATE INDEX IF NOT EXISTS experiment_01_B_C_A_D_idx ON experiment_01 (B, C, A, D);
CREATE INDEX IF NOT EXISTS experiment_01_B_C_D_A_idx ON experiment_01 (B, C, D, A);
CREATE INDEX IF NOT EXISTS experiment_01_B_D_A_C_idx ON experiment_01 (B, D, A, C);
CREATE INDEX IF NOT EXISTS experiment_01_B_D_C_A_idx ON experiment_01 (B, D, C, A);
CREATE INDEX IF NOT EXISTS experiment_01_C_A_B_D_idx ON experiment_01 (C, A, B, D);
CREATE INDEX IF NOT EXISTS experiment_01_C_A_D_B_idx ON experiment_01 (C, A, D, B);
CREATE INDEX IF NOT EXISTS experiment_01_C_B_A_D_idx ON experiment_01 (C, B, A, D);
CREATE INDEX IF NOT EXISTS experiment_01_C_B_D_A_idx ON experiment_01 (C, B, D, A);
CREATE INDEX IF NOT EXISTS experiment_01_C_D_A_B_idx ON experiment_01 (C, D, A, B);
CREATE INDEX IF NOT EXISTS experiment_01_C_D_B_A_idx ON experiment_01 (C, D, B, A);
CREATE INDEX IF NOT EXISTS experiment_01_D_A_B_C_idx ON experiment_01 (D, A, B, C);
CREATE INDEX IF NOT EXISTS experiment_01_D_A_C_B_idx ON experiment_01 (D, A, C, B);
CREATE INDEX IF NOT EXISTS experiment_01_D_B_A_C_idx ON experiment_01 (D, B, A, C);
CREATE INDEX IF NOT EXISTS experiment_01_D_B_C_A_idx ON experiment_01 (D, B, C, A);
CREATE INDEX IF NOT EXISTS experiment_01_D_C_A_B_idx ON experiment_01 (D, C, A, B);
CREATE INDEX IF NOT EXISTS experiment_01_D_C_B_A_idx ON experiment_01 (D, C, B, A);



